export type Locale = "en" | "es";

export const copy = {
  en: {
    skip: "Skip to content",
    wordmark: "HGS",
    langLabel: "ES",
    chapters: [
      { id: "intro", n: "01", label: "Intro" },
      { id: "practice", n: "02", label: "Practice" },
      { id: "startup", n: "03", label: "Startup" },
      { id: "tenure", n: "04", label: "Tenure" },
      { id: "selected", n: "05", label: "Selected" },
      { id: "credentials", n: "06", label: "Credentials" },
      { id: "stack", n: "07", label: "Stack" },
      { id: "close", n: "08", label: "Close" },
    ],
    heroKicker: "Software Engineer  ·  Product Developer",
    heroName: ["Harol", "G. Salgado"],
    heroDek:
      "I design and ship systems people actually use — from SAP floors to local commerce, with generative AI in the loop.",
    heroNow: "Now  ·  Full Stack Developer at MIGOZZ",
    heroMeta: ["Colombia", "TypeScript", "SAP / Cloud / AI"],
    scroll: "Scroll the issue",
    issue: "Issue 01  —  Selected Work",
    practiceEyebrow: "02  —  Practice",
    practiceTitle: "A product engineer who still writes the boring parts.",
    practiceBody:
      "I work mainly in the JavaScript and TypeScript ecosystem — React, Next.js, Node — and I have designed serverless architectures on AWS. The interesting part is not the stack. It is putting generative AI, cloud, and a real interface on the same table, then making it hold in production.",
    practiceAside:
      "Interfaces, APIs, Unity, Arduino. Same habit: observe the constraint, then ship the smallest system that solves it.",
    bento: [
      { k: "Full stack", v: "Web products with React, Next.js, Node, SQL and NoSQL." },
      { k: "AI", v: "Generative models, semantic search, automation that escalates to a human." },
      { k: "Cloud", v: "Serverless on AWS, containers, CI/CD, Google Cloud and Firebase." },
      { k: "Mobile", v: "Cross-platform with Flutter, native Android when the product needs it." },
      { k: "Game & IoT", v: "Unity and C#, embedded prototypes with Arduino and sensors." },
      { k: "Based", v: "Colombia. Available for product work, platforms, and SAP-adjacent systems." },
    ],
    startupEyebrow: "03  —  Startup",
    startupCompany: "MIGOZZ",
    startupRole: "Full Stack Developer",
    startupPeriod: "Sep 28, 2026 – Present",
    startupStatus: "Current",
    startupBody:
      "A social platform for creators, influencers, brands and artists — Android, iOS and Web. I work on the live product: keeping it healthy, testing it, and shipping what comes next.",
    startupDuties: [
      { n: "01", k: "Maintenance", v: "Keeping the live app stable across Android, iOS and Web." },
      { n: "02", k: "QA testing", v: "Testing features and catching regressions before users do." },
      { n: "03", k: "Development", v: "Building new features across the Flutter app and Firebase backend." },
      { n: "04", k: "Issues & PRs", v: "Resolving issues and shipping the fixes through pull requests." },
    ],
    startupLinks: {
      web: "https://migozz.com",
      play: "https://play.google.com/store/apps/details?id=com.migozz.migozzApp",
      apple: "https://apps.apple.com/co/app/migozz/id6502121020",
    },
    startupWeb: "migozz.com",
    startupStack: ["Flutter", "Dart", "Firebase", "Cloud Functions", "Stripe"],
    tenureEyebrow: "04  —  Tenure",
    tenureStatus: "Previous",
    tenureCompany: "Mitsubishi Electric de Colombia",
    tenureRole: "Software Developer — SAP / SAP Fiori",
    tenurePlace: "Bello  ·  Jan 2026 – Jul 2026",
    tenureBeats: [
      {
        n: "01",
        title: "Migrate without stopping the plant",
        body: "Led, with the team, a full-stack migration of SAP services for five business areas. Continuity first. Then adaptation to how each area actually works.",
      },
      {
        n: "02",
        title: "OData and Fiori, kept lean",
        body: "Developed and refined OData services and SAP Fiori / SAPUI5 apps. Less payload, cleaner code, a surface consultants can maintain.",
      },
      {
        n: "03",
        title: "Incidents before production",
        body: "Diagnosed and resolved defects in SAP features and services. Functional tests first. Then release.",
      },
    ],
    selectedEyebrow: "05  —  Selected work",
    selectedTitle: "Software I have built.",
    selectedLead:
      "Eight projects where I was the developer: enterprise AI, local commerce, academic ops, games and sensors.",
    projects: [
      {
        id: "sabaneta",
        shot: "shots/sabaneta.jpg",
        alt: "Screenshot of the Hecho en Sabaneta home page",
        tag: "Commerce  ·  Live",
        title: "Hecho en Sabaneta",
        dek: "Local commerce platform: directory, catalog, cart, and events for the municipality.",
        href: "https://hechoensabaneta.com",
        stack: ["TypeScript", "Next.js", "Firebase", "Google Cloud"],
      },
      {
        id: "arcoiris",
        shot: "shots/arcoiris.jpg",
        alt: "Screenshot of the Arcoiris Zapatería home page",
        tag: "Services  ·  Live",
        title: "Arcoiris Zapatería",
        dek: "Service site for a family workshop in Medellín. Fifty-plus trades, before/after, guided diagnosis to WhatsApp.",
        href: "https://arcoiriszapateria.com",
        stack: ["TypeScript", "Next.js", "Firebase", "Google Cloud"],
      },
      {
        id: "aria",
        client: "Arix Group",
        clientHref: "https://arixgroup.com.co/",
        hue: 265,
        tag: "Generative AI  ·  SAP",
        title: "ARIA",
        dek: "Intelligent assistant for SAP processes. Serverless on AWS, Bedrock, OpenSearch, and a human escalation path when the model cannot close the ticket.",
        stack: ["AWS", "Lambda", "Bedrock", "OpenSearch", "Python", "React"],
      },
      {
        id: "sena",
        client: "Built during my training at SENA",
        institutional: true,
        href: "https://senacloud.netlify.app/",
        logo: "sena-logo.svg",
        hue: 150,
        tag: "Platform  ·  Live",
        title: "SENA Cloud",
        dek: "Academic and administrative ops for instructors, admins, and superadmins.",
        stack: ["TypeScript", "React", "MongoDB"],
      },
      {
        id: "chaman",
        client: "Inversiones Amazónica S.A.S.",
        hue: 300,
        tag: "AI  ·  Ops",
        title: "Chaman Tarot",
        dek: "Dashboard for readings. Predictions via AI, automation with Make, data on Supabase.",
        stack: ["React", "Supabase", "Make"],
      },
      {
        id: "cashwin",
        client: "Inversiones Amazónica S.A.S.",
        hue: 25,
        tag: "Game",
        title: "CashWin",
        dek: "Realtime multiplayer dice. Photon PUN 2, MercadoPago, Unity and C#.",
        stack: ["Unity", "C#", "Photon"],
      },
      {
        id: "sensores",
        client: "Built during my training at SENA",
        institutional: true,
        logo: "sena-logo.svg",
        hue: 195,
        tag: "IoT",
        title: "SensoresAPP",
        dek: "Arduino flood early-warning for nearby communities.",
        stack: ["Arduino", "C++", "IoT"],
      },
      {
        id: "farmacia",
        client: "Droguería Medifarma",
        hue: 170,
        tag: "Internal",
        title: "Farmacia Admin",
        dek: "Private inventory, sales, and reporting for pharmacies.",
        stack: ["React", "MongoDB"],
      },
    ],
    credEyebrow: "06  —  Credentials",
    credTitle: "Education and credentials.",
    credLead:
      "Degrees, courses and recognitions earned along the way. Identity document numbers are hidden.",
    credGroups: [
      {
        k: "Degrees",
        items: [
          { img: "tecnologo-ads", title: "Technologist in Software Analysis and Development", meta: "SENA  ·  Sep 2026" },
          { img: "tecnico-sistemas", title: "Systems Technician", meta: "SENA  ·  Nov 2023" },
          { img: "bachiller", title: "Academic High School Diploma", meta: "I.E. Santo Domingo  ·  Dec 2023" },
        ],
      },
      {
        k: "Courses",
        items: [
          { img: "curso-testing", title: "Software Testing", meta: "SENA  ·  48 h  ·  Oct 2025" },
          { img: "curso-python-eda", title: "Exploratory Data Analysis with Python", meta: "SENA  ·  48 h  ·  May 2024" },
          { img: "curso-python-limpieza", title: "Data Cleaning and Transformation with Python", meta: "SENA  ·  48 h  ·  Sep 2024" },
          { img: "curso-english-1", title: "English Does Work, Level 1", meta: "SENA  ·  48 h  ·  Nov 2024" },
          { img: "curso-english-2", title: "English Does Work, Level 2", meta: "SENA  ·  48 h  ·  Jul 2025" },
        ],
      },
      {
        k: "Recognitions",
        items: [
          { img: "orgullo-sena-2024", title: "Orgullo SENA 2024, Technical Performance", meta: "SENA Antioquia  ·  2024" },
          { img: "aprendiz-integral", title: "Aprendiz Integral, Special Recognition", meta: "SENA CTPGA  ·  Sep 2023" },
          { img: "reconocimiento-integralidad", title: "Recognition for all-round professional training", meta: "SENA CTPGA" },
        ],
      },
    ],
    credView: "View certificate",
    credClose: "Close",
    stackEyebrow: "07  —  Stack",
    stackTitle: "Tools I reach for without thinking.",
    stackGroups: [
      { k: "Interface", v: "HTML, CSS, Sass, Tailwind, React, Next.js, Vue, Flutter" },
      { k: "Runtime", v: "TypeScript, Node, Python, Dart, C#, C++" },
      { k: "Data", v: "PostgreSQL, MongoDB, MySQL, Supabase, Firebase, OpenSearch" },
      { k: "Cloud", v: "AWS, Lambda, API Gateway, Bedrock, Docker, GitHub Actions" },
      { k: "SAP", v: "Fiori, SAPUI5, OData, process support, incident analysis" },
      { k: "Now", v: "Generative AI in product, serverless AWS, Flutter, Linux, DevOps" },
    ],
    closeEyebrow: "08  —  Close",
    closeTitle: "Write to me.",
    closeBody:
      "Product work, platforms, SAP-adjacent systems, or a strange brief that needs a working interface. Colombia. Reply in Spanish or English.",
    email: "haroldguerrerosena@gmail.com",
    links: [
      { label: "GitHub", href: "https://github.com/DevCat-HGS" },
      { label: "LinkedIn", href: "https://www.linkedin.com/in/harold-salgado-498a60354/" },
      { label: "DevTools", href: "https://github.com/DevCat-HGS/DevTools" },
    ],
    footer: "Harol G. Salgado  ·  Software Engineer",
    visit: "Open site",
    cv: { label: "Download CV", href: "cv/Harol_Guerrero_CV_EN.pdf" },
    clientLabel: "Client",
    institutionalLabel: "Institutional project",
    trademarkNote:
      "SENA and its logo are the property of Servicio Nacional de Aprendizaje. They are used here only to identify the institution these projects were built for, and do not imply endorsement.",
  },
  es: {
    skip: "Saltar al contenido",
    wordmark: "HGS",
    langLabel: "EN",
    chapters: [
      { id: "intro", n: "01", label: "Inicio" },
      { id: "practice", n: "02", label: "Oficio" },
      { id: "startup", n: "03", label: "Startup" },
      { id: "tenure", n: "04", label: "Cargo" },
      { id: "selected", n: "05", label: "Obra" },
      { id: "credentials", n: "06", label: "Credenciales" },
      { id: "stack", n: "07", label: "Stack" },
      { id: "close", n: "08", label: "Cierre" },
    ],
    heroKicker: "Software Engineer  ·  Product Developer",
    heroName: ["Harol", "G. Salgado"],
    heroDek:
      "Diseño y entrego sistemas que la gente usa de verdad — del piso SAP al comercio local, con IA generativa en el circuito.",
    heroNow: "Ahora  ·  Desarrollador Full Stack en MIGOZZ",
    heroMeta: ["Colombia", "TypeScript", "SAP / Cloud / IA"],
    scroll: "Desplaza el número",
    issue: "Número 01  —  Trabajo seleccionado",
    practiceEyebrow: "02  —  Oficio",
    practiceTitle: "Un product engineer que todavía escribe las partes aburridas.",
    practiceBody:
      "Trabajo sobre todo en el ecosistema JavaScript y TypeScript — React, Next.js, Node — y he diseñado arquitecturas serverless en AWS. Lo interesante no es el stack. Es poner IA generativa, cloud y una interfaz real en la misma mesa, y que aguante en producción.",
    practiceAside:
      "Interfaces, APIs, Unity, Arduino. El mismo hábito: observar la restricción y entregar el sistema más pequeño que la resuelve.",
    bento: [
      { k: "Full stack", v: "Productos web con React, Next.js, Node, SQL y NoSQL." },
      { k: "IA", v: "Modelos generativos, búsqueda semántica, automatización que escala a un humano." },
      { k: "Cloud", v: "Serverless en AWS, contenedores, CI/CD, Google Cloud y Firebase." },
      { k: "Mobile", v: "Multiplataforma con Flutter, Android nativo cuando el producto lo pide." },
      { k: "Game e IoT", v: "Unity y C#, prototipos embebidos con Arduino y sensores." },
      { k: "Base", v: "Colombia. Disponible para producto, plataformas y sistemas junto a SAP." },
    ],
    startupEyebrow: "03  —  Startup",
    startupCompany: "MIGOZZ",
    startupRole: "Desarrollador Full Stack",
    startupPeriod: "28 sep. 2026 – Actualidad",
    startupStatus: "Actual",
    startupBody:
      "Una plataforma social para creadores, influencers, marcas y artistas — Android, iOS y Web. Trabajo sobre el producto en vivo: mantenerlo sano, probarlo y entregar lo que viene.",
    startupDuties: [
      { n: "01", k: "Mantenimiento", v: "Mantener estable la app en vivo en Android, iOS y Web." },
      { n: "02", k: "QA testing", v: "Probar funcionalidades y detectar regresiones antes que los usuarios." },
      { n: "03", k: "Desarrollo", v: "Construir nuevas funciones en la app Flutter y el backend Firebase." },
      { n: "04", k: "Issues y PRs", v: "Resolver issues y entregar las correcciones mediante pull requests." },
    ],
    startupLinks: {
      web: "https://migozz.com",
      play: "https://play.google.com/store/apps/details?id=com.migozz.migozzApp",
      apple: "https://apps.apple.com/co/app/migozz/id6502121020",
    },
    startupWeb: "migozz.com",
    startupStack: ["Flutter", "Dart", "Firebase", "Cloud Functions", "Stripe"],
    tenureEyebrow: "04  —  Cargo",
    tenureStatus: "Anterior",
    tenureCompany: "Mitsubishi Electric de Colombia",
    tenureRole: "Desarrollador de Software — SAP / SAP Fiori",
    tenurePlace: "Bello  ·  ene. 2026 – jul. 2026",
    tenureBeats: [
      {
        n: "01",
        title: "Migrar sin parar la planta",
        body: "Lideré junto al equipo la migración full stack de servicios SAP para cinco áreas. Primero continuidad operativa. Después adaptación a cómo trabaja cada área.",
      },
      {
        n: "02",
        title: "OData y Fiori, en magro",
        body: "Desarrollé y ajusté servicios OData y apps SAP Fiori / SAPUI5. Menos payload, código más limpio, una superficie que un consultor puede mantener.",
      },
      {
        n: "03",
        title: "Incidencias antes de producción",
        body: "Analicé y resolví defectos en funcionalidades y servicios SAP. Pruebas funcionales primero. Después el pase.",
      },
    ],
    selectedEyebrow: "05  —  Obra seleccionada",
    selectedTitle: "Software que he desarrollado.",
    selectedLead:
      "Ocho proyectos donde fui el desarrollador: IA empresarial, comercio local, operación académica, juegos y sensores.",
    projects: [
      {
        id: "sabaneta",
        shot: "shots/sabaneta.jpg",
        alt: "Captura de la página de inicio de Hecho en Sabaneta",
        tag: "Comercio  ·  En vivo",
        title: "Hecho en Sabaneta",
        dek: "Plataforma de comercio local: directorio, catálogo, carrito y eventos del municipio.",
        href: "https://hechoensabaneta.com",
        stack: ["TypeScript", "Next.js", "Firebase", "Google Cloud"],
      },
      {
        id: "arcoiris",
        shot: "shots/arcoiris.jpg",
        alt: "Captura de la página de inicio de Arcoiris Zapatería",
        tag: "Servicios  ·  En vivo",
        title: "Arcoiris Zapatería",
        dek: "Sitio de servicios para un taller familiar en Medellín. Más de cincuenta oficios, antes/después, diagnóstico guiado a WhatsApp.",
        href: "https://arcoiriszapateria.com",
        stack: ["TypeScript", "Next.js", "Firebase", "Google Cloud"],
      },
      {
        id: "aria",
        client: "Arix Group",
        clientHref: "https://arixgroup.com.co/",
        hue: 265,
        tag: "IA generativa  ·  SAP",
        title: "ARIA",
        dek: "Asistente inteligente para procesos SAP. Serverless en AWS, Bedrock, OpenSearch, y un escalamiento humano cuando el modelo no cierra el ticket.",
        stack: ["AWS", "Lambda", "Bedrock", "OpenSearch", "Python", "React"],
      },
      {
        id: "sena",
        client: "Desarrollado durante mi formación en el SENA",
        institutional: true,
        href: "https://senacloud.netlify.app/",
        logo: "sena-logo.svg",
        hue: 150,
        tag: "Plataforma  ·  En vivo",
        title: "SENA Cloud",
        dek: "Operación académica y administrativa para instructores, admins y superadmins.",
        stack: ["TypeScript", "React", "MongoDB"],
      },
      {
        id: "chaman",
        client: "Inversiones Amazónica S.A.S.",
        hue: 300,
        tag: "IA  ·  Ops",
        title: "Chaman Tarot",
        dek: "Dashboard de lecturas. Predicciones con IA, automatización con Make, datos en Supabase.",
        stack: ["React", "Supabase", "Make"],
      },
      {
        id: "cashwin",
        client: "Inversiones Amazónica S.A.S.",
        hue: 25,
        tag: "Juego",
        title: "CashWin",
        dek: "Dados multijugador en tiempo real. Photon PUN 2, MercadoPago, Unity y C#.",
        stack: ["Unity", "C#", "Photon"],
      },
      {
        id: "sensores",
        client: "Desarrollado durante mi formación en el SENA",
        institutional: true,
        logo: "sena-logo.svg",
        hue: 195,
        tag: "IoT",
        title: "SensoresAPP",
        dek: "Alerta temprana de inundaciones con Arduino para comunidades cercanas.",
        stack: ["Arduino", "C++", "IoT"],
      },
      {
        id: "farmacia",
        client: "Droguería Medifarma",
        hue: 170,
        tag: "Interno",
        title: "Farmacia Admin",
        dek: "Inventario, ventas y reportes privados para farmacias.",
        stack: ["React", "MongoDB"],
      },
    ],
    credEyebrow: "06  —  Credenciales",
    credTitle: "Formación y credenciales.",
    credLead:
      "Títulos, cursos y reconocimientos obtenidos en el camino. Los números de documento de identidad están ocultos.",
    credGroups: [
      {
        k: "Títulos",
        items: [
          { img: "tecnologo-ads", title: "Tecnólogo en Análisis y Desarrollo de Software", meta: "SENA  ·  sep. 2026" },
          { img: "tecnico-sistemas", title: "Técnico en Sistemas", meta: "SENA  ·  nov. 2023" },
          { img: "bachiller", title: "Bachiller Académico", meta: "I.E. Santo Domingo  ·  dic. 2023" },
        ],
      },
      {
        k: "Cursos",
        items: [
          { img: "curso-testing", title: "Pruebas de Software - Testing", meta: "SENA  ·  48 h  ·  oct. 2025" },
          { img: "curso-python-eda", title: "Análisis Exploratorio de Datos en Python", meta: "SENA  ·  48 h  ·  may. 2024" },
          { img: "curso-python-limpieza", title: "Limpieza y Transformación de Datos con Python", meta: "SENA  ·  48 h  ·  sep. 2024" },
          { img: "curso-english-1", title: "English Does Work, Nivel 1", meta: "SENA  ·  48 h  ·  nov. 2024" },
          { img: "curso-english-2", title: "English Does Work, Nivel 2", meta: "SENA  ·  48 h  ·  jul. 2025" },
        ],
      },
      {
        k: "Reconocimientos",
        items: [
          { img: "orgullo-sena-2024", title: "Orgullo SENA 2024, Desempeño Técnico", meta: "SENA Antioquia  ·  2024" },
          { img: "aprendiz-integral", title: "Aprendiz Integral, Reconocimiento Especial", meta: "SENA CTPGA  ·  sep. 2023" },
          { img: "reconocimiento-integralidad", title: "Reconocimiento por su integralidad en la formación", meta: "SENA CTPGA" },
        ],
      },
    ],
    credView: "Ver certificado",
    credClose: "Cerrar",
    stackEyebrow: "07  —  Stack",
    stackTitle: "Herramientas que uso sin pensarlo.",
    stackGroups: [
      { k: "Interfaz", v: "HTML, CSS, Sass, Tailwind, React, Next.js, Vue, Flutter" },
      { k: "Runtime", v: "TypeScript, Node, Python, Dart, C#, C++" },
      { k: "Datos", v: "PostgreSQL, MongoDB, MySQL, Supabase, Firebase, OpenSearch" },
      { k: "Cloud", v: "AWS, Lambda, API Gateway, Bedrock, Docker, GitHub Actions" },
      { k: "SAP", v: "Fiori, SAPUI5, OData, soporte de procesos, análisis de incidencias" },
      { k: "Ahora", v: "IA generativa en producto, serverless AWS, Flutter, Linux, DevOps" },
    ],
    closeEyebrow: "08  —  Cierre",
    closeTitle: "Escríbeme.",
    closeBody:
      "Producto, plataformas, sistemas junto a SAP, o un brief raro que necesite una interfaz que funcione. Colombia. Respondo en español o en inglés.",
    email: "haroldguerrerosena@gmail.com",
    links: [
      { label: "GitHub", href: "https://github.com/DevCat-HGS" },
      { label: "LinkedIn", href: "https://www.linkedin.com/in/harold-salgado-498a60354/" },
      { label: "DevTools", href: "https://github.com/DevCat-HGS/DevTools" },
    ],
    footer: "Harol G. Salgado  ·  Software Engineer",
    visit: "Abrir sitio",
    cv: { label: "Descargar CV", href: "cv/Harol_Guerrero_CV_ES.pdf" },
    clientLabel: "Cliente",
    institutionalLabel: "Proyecto institucional",
    trademarkNote:
      "SENA y su logo son propiedad del Servicio Nacional de Aprendizaje. Se usan aquí solo para identificar la institución para la que se desarrollaron estos proyectos, y no implican respaldo.",
  },
} as const;
